version: '3.8'
services:
  gateway:
    build: ./server
    container_name: explore_with_me
    ports:
      - "8080:8080"
    depends_on:
      - db service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ./statistic
    container_name: statistic_ewm
    ports:
      - "9090:9090"
    depends_on:
      - db statistic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/statistic
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  db service:
    image: postgres:13.7-alpine
    container_name: postgres_db_shareit
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db statistic:
    image: postgres:13.7-alpine
    container_name: postgres_db_shareit
    ports:
      - "6542:5433"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root