version: '3.8'
services:
  server:
    build: ./server
    container_name: explore_with_me
    ports:
      - "8080:8080"
    depends_on:
      - db_service
    environment:
      - EWM_STATISTIC_URL=http://statistic:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_service:5432/explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  statistic:
    build: ./statistic
    container_name: statistic_ewm
    ports:
      - "9090:9090"
    depends_on:
      - db_statistic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_statistic:5432/statistic
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db_service:
    image: postgres:13.7-alpine
    container_name: postgres_db_ewm_server
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db_statistic:
    image: postgres:13.7-alpine
    container_name: postgres_db_statistic
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root